openapi: "3.0.1"
info:
  title: Todo List API
  version: "1.0"

paths:
  /todos:
    get:
      summary: Get all todos
      responses:
        '200':
          description: OK

    post:
      summary: Create a todo
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                completed:
                  type: boolean
              required:
                - title
      responses:
        '201':
          description: Todo created

  /todos/{id}:
    delete:
      summary: Delete a todo
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        '204':
          description: Deleted successfully
